# ???? WEB ????
server.port=9049



# ????? utf-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
server.servlet.encoding.charset=utf-8

# MyBatis ??
logging.level.edu.neu.oaas.mapper=DEBUG
mybatis.config-location=classpath:/mybatis-config.xml
mybatis.type-aliases-package=edu.neu.oaas.pojo

# DataSource Configuration (Kingbase)
spring.datasource.url=jdbc:kingbase8://localhost:54321/demo2
spring.datasource.username=root
spring.datasource.password=528846
spring.datasource.driver-class-name=com.kingbase8.Driver

# 会话配置
server.servlet.session.timeout=30m
spring.session.store-type=jdbc
spring.session.jdbc.initialize-schema=always
spring.session.jdbc.schema=classpath:org/springframework/session/jdbc/schema-postgresql.sql
spring.session.jdbc.table-name=SPRING_SESSION
spring.session.cookie.same-site=None
spring.session.cookie.secure=true

# 指定数据库平台
spring.sql.init.platform=postgresql

# application.properties
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=50MB

#visitor.counter.file=/OAASystem/src/main/resources/static/visitor-counter.txt

# 缓存配置
spring.cache.type=jcache
spring.cache.jcache.config=classpath:ehcache.xml
# 启用缓存统计
spring.cache.jcache.provider=org.ehcache.jsr107.EhcacheCachingProvider

